### ISSUE TITLE
go test failed with go1.15rc1 , report "conversion from uint64 to string yields a string of one rune, not a string of digits"

### ISSUE THREAD

**Issue by gudigudi** [minio/simdjson-go#17]
env: go version go1.15rc1 darwin/amd64
go test result:
./parsed_json.go:903:34: conversion from uint64 to string yields a string of one rune, not a string of digits (did you mean fmt.Sprint(x)?)
./parsed_json.go:985:68: conversion from uint64 to string yields a string of one rune, not a string of digits (did you mean fmt.Sprint(x)?)
./parsed_object.go:173:65: conversion from uint64 to string yields a string of one rune, not a string of digits (did you mean fmt.Sprint(x)?)

**Comment by fwessels** [comment]
Should be fixed by 652c37a
