### ISSUE TITLE
Parse from io.Reader

### ISSUE THREAD

**Issue by kwiesmueller** [minio/simdjson-go#20]
I'm currently using simdjson-go for the first time to parse a very big array.
It's great and brought a big performance boost.
One question though, is it a design decision to only take a full byte stream and not a reader?

Compared to encoding/json this is significantly faster, but takes more memory (the entire document).
It would be interesting to have a way around this and I wanted to know if it's even possible with how the library works right now.

**Comment by fwessels** [comment]
Nice to hear that it brought a good speedup, you may look at https://github.com/minio/minio/blob/master/pkg/s3select/simdj/reader.go for some inspiration about streaming. 

Ultimately the the parsed document is contained in memory, in case your data is  newline delimited json you can work in batches, if it is a single document then there is no way (at the moment) to purge previous parts of the tape  format.

**Comment by kwiesmueller** [comment]
Sadly the input is not ND but a json array :-/
But thanks already.
If I have some time I'll play around a bit more. 
Would you consider it feasible to discard parts of the object that have already been iterated over. Like in an array the entries after calling iter.Advance. If it's not really doable directly, I could imagine something like a obj.Discard to discard what the developer knows won't be required again.

Really not familiar with json parsing so far, just thinking out loud :D

**Comment by fwessels** [comment]
Yeah, it would be really nice to be able to discard previous parts of the tape once no longer needed. We're not yet fully happy with the iterator implementation, it could certainly be made more user friendly and more flexible (we would be open to a PR for that, even a secondary interface/API could work).

Releasing previous parts of the tape could also tie in nicely with being able to set `ALWAYS_COPY_STRINGS` to off for better performance (which is on by default now in order  to support streaming use case,  see  https://github.com/minio/simdjson-go#non-streaming-use-cases ).
