### ISSUE TITLE
Benchmarks are outdated

### ISSUE THREAD

**Issue by WillAbides** [minio/simdjson-go#35]
I was unable to reproduce the published benchmark results on the current HEAD, but I was able to reproduce them by reverting to an old commit. It appears that performance has degraded since then. From what I can tell, removing the ability to set `GOLANG_NUMBER_PARSING = false` had a significant impact.

[This gist](https://gist.github.com/WillAbides/8d68cedaf410b0cf3e8299ae4ab2727c) has more details about my attempts to reproduce the result.

**Comment by klauspost** [comment]
@WillAbides See PR with updates numbers. AMD Ryzen 3950, Go 1.16.2 FWIW
