### ISSUE TITLE
Benchmarks are misleading

### ISSUE THREAD

**Issue by mhr3** [minio/simdjson-go#38]
The benchmarks in benchmarks_test.go aren't really comparing apples to apples, the simdjson benchmark is only parsing the JSON, while the other benchmarks are parsing it and building an interface{}-typed object to represent the data.

**Comment by harshavardhana** [comment]
You need to first understand the purpose of this library, it is not a drop in replacement of JSON parsing.

It is meant to introduce a newer technique for JSON parsing that is meant for specific streaming use cases.

The parsed json is implemented as a generic struct that allows for streaming approach to handle the large JSON blobs to be parsed.

This approach is essentially then SIMD optimized it may not work for all use cases.  

The benchmarks kept are showing the exact difference of  parsing, providing an interface structure makes json 
Marshal not do any reflection so in essence they both are doing the same thing.

**Comment by klauspost** [comment]
@mhr3 As stated on the README

>Though simdjson provides different output than traditional unmarshal functions this can give an overview of the expected performance for reading specific data in JSON.

> Below is a performance comparison to Golang's standard package encoding/json based on the same set of JSON test files, unmarshal to interface{}.

**Comment by mhr3** [comment]
> You need to first understand the purpose of this library, it is not a drop in replacement of JSON parsing.

That's exactly my point, the current benchmarks make it seem like simdjson is magic that does everything 10x faster with literally 20 memory allocations (even though any string in golang will cause an alloc).

> Below is a performance comparison to Golang's standard package encoding/json based on the same set of JSON test files, unmarshal to interface{}.

Yet the unmarshal to interface{} is pretty expensive and the simdjson benchmark isn't doing it , the benchmarks would be completely accurate if the simdjson code was also constructing the interface{}, which is literally two lines of code: 
```
iter := parsedJson.Iter()
iter.Interface()
```

**Comment by klauspost** [comment]
@mhr3 This is what is needed to unmarshal arbitrary JSON and inspect values. Creating an interface representation is pointless if you need to look up specific values, say claims in a JWT (token).

It may not cover your specific needs, but you are welcome to do your own benchmarks.
