### ISSUE TITLE
Impact of GOAMD64 on simdjson-go

### ISSUE THREAD

**Issue by rabbbit** [minio/simdjson-go#69]
Hi!

Go 1.18 added the GOAMD64 build environment variable (https://tip.golang.org/doc/go1.18#amd64, https://github.com/golang/go/wiki/MinimumRequirements#amd64).

On the surface, it would seem that GOAMD64=v3+ should affect performance of this package, since it's adding a bunch of SIMD instructions.

Could you please verify that assumption? Is there any relationship between the environmental variable and this project?

Thanks,

**Comment by klauspost** [comment]
Parsing requires v3. Features are detected runtime, so the flags doesn't do anything.

**Comment by klauspost** [comment]
(and it there is no real benefit from it)

**Comment by rabbbit** [comment]
Thanks!
