### ISSUE TITLE
Removing array elements

### ISSUE THREAD

**Issue by dlouwers** [minio/simdjson-go#71]
Hi,

We are currently looking at this library to achieve the following:

- Quickly inspect the JSON
- Remove elements from an inner array based on certain business rules
- Emit the JSON buffer minus the filtered array elements

Is this possible with this library? I have not found methods to nil an object or array element so far.

Best,

Dirk

**Comment by klauspost** [comment]
[In-place Value Replacement](https://github.com/minio/simdjson-go#in-place-value-replacement) is fairly limited.

You would have to add a "NOP" tape operator to be able to delete values completely.

**Comment by klauspost** [comment]
@dlouwers Have a look at https://github.com/minio/simdjson-go/pull/72

**Comment by harshavardhana** [comment]
Closing as fixed via #72
