### ISSUE TITLE
need the original c code that converted to the goasm

### ISSUE THREAD

**Issue by kkHAIKE** [minio/simdjson-go#74]
i can't found it from offical simdjson repo..😢

**Comment by harshavardhana** [comment]
Its linked at the first line on the README.md https://github.com/simdjson/simdjson

**Comment by kkHAIKE** [comment]
i means can't find `find_odd_backslash_sequences / find_structural_bits / find_whitespace_and_structurals ...` in simdjson repo...

maybe it's refactoring?

**Comment by harshavardhana** [comment]
> i means can't find `find_odd_backslash_sequences / find_structural_bits / find_whitespace_and_structurals ...` in simdjson repo...
> 
> maybe it's refactoring?
> 
> and I am trying to add arm64 support..

It won't be that easy @kkHAIKE you would have to work on it fully to figure it out. It is not c -> asm direct mapping AFAIK.
