### ISSUE TITLE
Delete null values

### ISSUE THREAD

**Issue by ivanjaros** [minio/simdjson-go#85]
I want to remove all null values from json. Presently I am doing it manually with bytes.Index() but it is not performing as good as I would like it to.

Since this has iterator, is there a way to walk the tree and delete null values and produce altered json? I see in documentation that I can delete(though I don't get it really with the typing) child elements. So I think it should be possible, any hints on how?

**Comment by fwessels** [comment]
This json library is primarily aimed at high performance parsing of JSON data.
Modifying the tape that is produced by the parser provides suboptimal performance, so this isn't a great use case for this library.
