### ISSUE TITLE
Parsing large JSON

### ISSUE THREAD

**Issue by mitar** [minio/simdjson-go#87]
I am building a tool which would extract data from a potentially large JSON. If data is ndjson, then this package already supports streaming support. But if data is in a large JSON array, or even worse, a large JSON array nested under one field in JSON object ([example](https://fdc.nal.usda.gov/fdc-datasets/FoodData_Central_branded_food_json_2024-04-18.zip) of such a file is `brandedDownload.json`), then it seems I have to first load into the memory the whole file before I can extract that data out. It would be nice if I could lazily construct the path and then iterate over the nested array, loading into the memory just the amount which is needed to iterate to the next array element.

**Comment by klauspost** [comment]
This is how it is designed. Maybe https://github.com/buger/jsonparser can help you.
